version: "3.8"

services:
  app:
    build: ../../site/sft_site
    command: sh -c "python manage.py makemigrations && python manage.py migrate && gunicorn --bind 0.0.0.0:8000 sft_site.wsgi:application"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - worker
    env_file:
      - ./ .env


  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  worker:
    build:
      context: ../../site/sft_site
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - .:/app
    links:
      - redis
    depends_on:
      - redis