# Generated by Django 5.1.1 on 2024-09-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название сертификата')),
                ('description', models.TextField(verbose_name='Описание сертификата')),
                ('image', models.ImageField(upload_to='certificates/', verbose_name='Изображение сертификата')),
                ('issued_at', models.DateField(verbose_name='Дата выдачи')),
                ('expired_at', models.DateField(verbose_name='Дата истечения срока действия')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('description', models.TextField(verbose_name='Описание проекта')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Изображение проекта')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('bio', models.TextField(verbose_name='Биография')),
                ('image', models.ImageField(upload_to='team/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Член команды',
                'verbose_name_plural': 'Команда',
            },
        ),
        migrations.AlterField(
            model_name='advantage',
            name='description',
            field=models.TextField(verbose_name='Описание преимущества'),
        ),
        migrations.AlterField(
            model_name='advantage',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название преимущества'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(verbose_name='Описание услуги'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='services/', verbose_name='Изображение услуги'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название услуги'),
        ),
    ]
